version: '3.8'
services:
  app:
    container_name: backend-container
    build:
      context: ./backend
      target: development
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
    volumes:
      - ./backend:/app
  react-app:
    container_name: frontend-container
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    links:
      - app
    depends_on:
      - app
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
